cc_binary(
    name = "rocksdb_json_loader",
    srcs = ["RocksDbJsonLoader.cpp"],
    deps = [
        "//services/http/data_source:rocksdb_utils",
        "//external:gflags",
        "//external:glog",
        "//external:rocksdb",
    ],
)
