package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_library(
    name = "nlohmann_json",
    includes = [
        "single_include/",
    ],
    srcs = [
    ],
    hdrs = [
        "single_include/nlohmann/json.hpp",
    ],
)
